### ISSUE TITLE
Collecting JMX Metrics from kafka brokers

### ISSUE THREAD

**Issue by lcalisi** [stealthly/minotaur#10]
How would recommend saving metrics from the kafka brokers themselves? It appears graphite instances are not running on the kafka nodes. They don't seem to publish to another node in the cluster. I do see JXM ports are open but their hidden because of the private IP's. Is the only way to pull down stats is to write a JMX client that saves them to a local file every X number of seconds and then download the results for offline analysis?

Thanks, Louis

**Comment by joestein** [comment]
You need to set that up. This is one reason case for supplying the tgz for kafka so you can bundle that in the configs using any of:
- Kafka metrics write to Kafka topic, consumers for graphite, riemann, etc https://github.com/stealthly/metrics-kafka
- Kafka writes to statsd https://github.com/airbnb/kafka-statsd-metrics2 
- JMX reporters for Kafka https://cwiki.apache.org/confluence/display/KAFKA/JMX+Reporters
